### ISSUE TITLE
MunkiAdmin Recipe uses .download file extension

### ISSUE THREAD

**Issue by hunty1** [autopkg/jleggat-recipes#14]
The munkiadmin receipe uses a .download file extension as the name of the folder that holds the cache. as a result that folder is not browseable in the finder, instead it is recognised as a safari web archive.

com.github.jleggat.MunkiAdmin.download

perhaps should be

com.github.jleggat.download.MunkAdmin

for example, similar download recipes identifiers:

com.github.autopkg.download.Adium
com.github.autopkg.download.AdobeAIR

**Comment by gregneagle** [comment]
Changing existing recipe identifiers brings its own set of issues: any child recipes that use these recipes would need to be changed -- including any or all recipe_overrides in use among all autopkg users all over the world...

Which is worse -- not being able to easily browse this folder in the Finder, or breaking a bunch of people's overrides? (I don't know the answer, and the answer is up to jleggat)

**Comment by jleggat** [comment]
Not going to mess with it.  Last time I changed things like that it caused problems for other people.  Sorry.
