### ISSUE TITLE
Download URL scheme changed

### ISSUE THREAD

**Issue by BestMacsBen** [autopkg/jleggat-recipes#32]
Looks like they changed their website. I was able to get it to download with these keys:
<key>SEARCH_PATTERN</key>
<string>class="btn my-btn freebtn header-trial-button" href="(?P&lt;url&gt;[^"]+)"</string>
<key>SEARCH_URL</key>
<string>http://lightpaper.42squares.in</string>

But can't get it to import into munki, probably because it now comes in a zip, which I'm not sure how to work around.

**Comment by jleggat** [comment]
Ok URL changes have been made.  Updated recipes to work with downloaded zip file.  See  0270e14

Thanks,
Jeremy
