### ISSUE TITLE
Change in Recipe Identifiers 

### ISSUE THREAD

**Issue by jlehikoinen** [autopkg/jleggat-recipes#7]
Hi!

Not exactly an issue, but more like a friendly reminder.

Changing recipe identifiers affects recipe override functionality. I just noticed this yesterday when MunkiAdmin recipe override couldn't find parent recipe. :)

You might want to check out this discussion: https://groups.google.com/forum/#!topic/autopkg-discuss/sgODZN4SzAw

**Comment by jleggat** [comment]
Thanks, my bad.  Definitely will plan on not changing them in the future.  Guess I got a little carried away with my changes that day.
