### ISSUE TITLE
Error running recipes

### ISSUE THREAD

**Issue by bjornbf** [autopkg/jleggat-recipes#9]
Hi

I have been using your recipe for a long time, but starting to day I get this error.

A Python exception occurred during the execution of autopkg, see the console log for more details.

[ERROR] UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 182: ordinal not in range(128)

Regards Bjørn

**Comment by paulbloch** [comment]
The problem is a mangled Description field.

            <key>description</key>
            <string>ack is a grep-like tool that is specifically created to make searching source code easier</string
Designed for programmers with large heterogeneous
        trees of source code, ack is written purely in
        portable Perl 5 and takes advantage of the power of
        Perl's regular expressions.>

**Comment by 48kRAM** [comment]
I have a pull request open to fix this issue. In the meantime, my forked version with the fix is available at:

https://github.com/48kRAM/jleggat-recipes.git

You can run 
autopkg repo-add https://github.com/48kRAM/jleggat-recipes
to use my version until the pull request is accepted.

**Comment by jleggat** [comment]
Thanks, changes have been pulled into my repo.
